# Generated by Django 5.0.4 on 2024-04-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionMallcomment',
            name='score',
            field=models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=5, verbose_name='评分'),
        ),
    ]
