# Generated by Django 5.0.4 on 2024-04-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fashionMallcart',
            options={'ordering': ['-add_date'], 'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
    ]
