# Generated by Django 5.0.4 on 2024-04-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fashionMallImagesAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('image', models.ImageField(upload_to='images/ad/%Y/%m/%d/', verbose_name='图片')),
                ('url', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('slug', models.SlugField(blank=True, default='home-banner', help_text='slug可以重复，用作广告位标识，如：banner-1', verbose_name='Slug')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'ordering': ['-sort'],
            },
        ),
    ]
