# Generated by Django 5.0.4 on 2024-04-15 01:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fashionMallOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('pay_method', models.PositiveSmallIntegerField(choices=[(1, '支付宝支付'), (2, '微信支付'), (3, '余额支付'), (4, '货到付款')], default=1, verbose_name='支付方式')),
                ('pay_status', models.PositiveSmallIntegerField(choices=[(0, '已过期'), (1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际支付')),
                ('pay_date', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('address', models.CharField(max_length=150, verbose_name='收货地址')),
                ('pick_up', models.CharField(max_length=50, verbose_name='收件人')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('shipping_method', models.PositiveSmallIntegerField(choices=[(1, '快递'), (2, '自提')], default=1, verbose_name='配送方式')),
                ('freight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'fashionMallOrder',
                'verbose_name_plural': 'fashionMallOrders',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='fashionMallOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('num', models.PositiveSmallIntegerField(default=1, verbose_name='数量')),
                ('specs', models.JSONField(blank=True, default=list, verbose_name='规格')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.fashionMallorder', verbose_name='订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.fashionMallsku', verbose_name='商品')),
            ],
            options={
                'verbose_name': 'fashionMallOrderProduct',
                'verbose_name_plural': 'fashionMallOrderProducts',
                'ordering': ['-add_date'],
            },
        ),
    ]
