# Generated by Django 5.0.4 on 2024-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionMallorderproduct',
            name='is_commented',
            field=models.BooleanField(default=False, verbose_name='是否评价'),
        ),
    ]
