# Generated by Django 5.0.4 on 2024-04-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionMalluseraddress',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='邮政编码'),
        ),
    ]
