# Generated by Django 5.0.3 on 2024-04-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fashionMallBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/%Y/%m', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'fashionMallBrand',
                'verbose_name_plural': 'fashionMallBrands',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='fashionMallSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('dash_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='划线价')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sale', models.IntegerField(default=0, verbose_name='销量')),
                ('is_sale', models.BooleanField(default=False, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='fashionMallSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
            ],
            options={
                'verbose_name': '规格',
                'verbose_name_plural': '规格',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='fashionMallCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.fashionMallcategory', verbose_name='父类')),
            ],
            options={
                'verbose_name': 'fashionMallCategory',
                'verbose_name_plural': 'fashionMallCategorys',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='fashionMallSpecsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('value', models.CharField(max_length=50, verbose_name='值')),
                ('specs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fashionMallspecs', verbose_name='规格')),
            ],
            options={
                'verbose_name': '规格值',
                'verbose_name_plural': '规格值',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='fashionMallSKUSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fashionMallsku', verbose_name='SKU')),
                ('value', models.ManyToManyField(blank=True, to='shop.fashionMallspecsvalue', verbose_name='值')),
            ],
            options={
                'verbose_name': 'SKU规格',
                'verbose_name_plural': 'SKU规格',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='fashionMallSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='详情')),
                ('is_sale', models.BooleanField(default=False, verbose_name='是否上架')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.fashionMallbrand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fashionMallcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-add_date'],
            },
        ),
        migrations.AddField(
            model_name='fashionMallsku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fashionMallspu', verbose_name='SPU'),
        ),
        migrations.CreateModel(
            name='fashionMallSPUImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spu/%Y/%m', verbose_name='图片')),
                ('status', models.BooleanField(default=False, verbose_name='是否显示')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fashionMallspu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': '商品图',
                'verbose_name_plural': '商品图',
                'ordering': ['-add_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='fashionMallspecsvalue',
            constraint=models.UniqueConstraint(fields=('specs', 'value'), name='unique_specs_value'),
        ),
    ]
