# Generated by Django 5.0.4 on 2024-04-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionMallcategory',
            name='is_floor',
            field=models.BooleanField(default=False, verbose_name='是否为楼层'),
        ),
    ]
