# Generated by Django 5.0.4 on 2024-04-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_fashionMallcategory_is_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fashionMallcategory',
            options={'ordering': ['-sort'], 'verbose_name': 'fashionMallCategory', 'verbose_name_plural': 'fashionMallCategorys'},
        ),
        migrations.AddField(
            model_name='fashionMallcategory',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='排序'),
        ),
    ]
