# Generated by Django 5.0.3 on 2024-03-28 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fashionMallArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.fashionMallarticlecategory', verbose_name='父类')),
            ],
            options={
                'verbose_name': 'fashionMallArticleCategory',
                'verbose_name_plural': 'fashionMallArticleCategorys',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='fashionMallArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
                ('keywords', models.CharField(blank=True, default='', max_length=150, verbose_name='关键词')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.fashionMallarticlecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': 'fashionMallArticleContent',
                'verbose_name_plural': 'fashionMallArticleContents',
                'ordering': ['-add_date'],
            },
        ),
    ]
